---

- name: Install Gunicorn
  pip: name=gunicorn virtualenv={{ virtualenv_path }}

- name: Create a directory for logs
  file: path={{ application_log_dir }}/gunicorn
        owner={{ application_user }}
        mode=0700
        state=directory

- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner={{ application_user }}
            group={{ application_group }}
            mode=0755
            backup=yes

- name: Initialise log rotation for Gunicorn
  template: src=gunicorn_log.j2
            dest='/etc/logrotate.d/{{ application_name }}-gunicorn.log'
            owner={{ application_user }}
            group={{ application_group }}
            mode=0644
